// ----------------------------------------------------------------------

export const fullName = [
  'Nike Air',
  'Samba',
  'Vans Old Skool',
  'Converse High Top',
  'DMERCE Special',
  'LV',
  

];
export const heading = [
  `Valorant`,
  `Assasins Creed`,
  `CSGO`,
  `Call of Duty`,
  `PUBG`,
  `Arkham Knights`,
  `FIFA 22`,
  `FIFA 23`,
];
export const price = [
  `$10.00`,
  `$20.00`,
  `$20.00`,
  `$20.00`,
  `$20.00`,
  `$20.00 `,
  `$20.00 `,
  `$20.00 `,
];
export const team2score = [1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 11, 12, 13];
export const team1score = [1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 11, 12, 13];

export const date = ['April 30, 2023'];

export const team1 = [
  `The Warriors`,
  `Tiger Commando`,
  `Vague Death Poets`,
  `Skin Crawlers`,
  `The Defenders`,
  `Abnormal Vigor`,
  `Thunderbeast`,
  `Leviathan  `,
];

export const team2 = [
  `Brookie Terminator`,
  `Close Shave`,
  `Purple Mafia`,
  `Victorious Squad`,
  `Bloodbath Architects`,
  `Medical Rebels`,
  `Untamed Warriors`,
  `Lords of Absurd`,
];

export const firstName = [
  'Mossie',
  'David',
  'Ebba',
  'Chester',
  'Eula',
  'Jaren',
  'Boyd',
  'Brady',
  'Aida',
  'Anastasia',
  'Gregoria',
  'Julianne',
  'Ila',
  'Elyssa',
  'Lucio',
  'Lewis',
  'Jacinthe',
  'Molly',
  'Brown',
  'Fritz',
  'Keon',
  'Ella',
  'Ken',
  'Whitney',
  'Monte',
  'Rose',
  'Shana',
  'Devon',
  'Jaleel',
  'Laury',
  'Brooks',
  'Bruce',
  'Avery',
  'Esperanza',
  'Helene',
  'Heloise',
  'Elinor',
  'Adeline',
  'Haley',
  'Anabelle',
];

export const lastName = [
  'Carroll',
  'Simonis',
  'Yost',
  'Hand',
  'Emmerich',
  'Wilderman',
  'Howell',
  'Sporer',
  'Boehm',
  'Morar',
  'Koch',
  'Reynolds',
  'Padberg',
  'Watsica',
  'Upton',
  'Yundt',
  'Pfeffer',
  'Parker',
  'Zulauf',
  'Treutel',
  'McDermott',
  'McDermott',
  'Cruickshank',
  'Parisian',
  'Auer',
  'Turner',
  'Dooley',
  'Wiegand',
  'Abbott',
  'Wisoky',
  'Fahey',
  'Satterfield',
  'Bahringer',
  'Schulist',
  'Durgan',
  'Carroll',
  'Jones',
  'Leffler',
  'Gutkowski',
  'Homenick',
];
